### ISSUE TITLE
Error with Mollie

### ISSUE THREAD

**Issue by FabLabs** [Bixie/Zoolander-ZOOcart-iDEAL#17]
Hi Malles,

Trying to get this plugin to work with Mollie.

I installed latest version and set the parameters as described.
I can't find the field in the Mollie dashboard to put the Webhook url?

I tried with the Live_ and Test_ API key, but end with a ''fatal error" after clicking payment.

I enabled /plugins/zoocart_payment/ideal/idealcheckout/includes/debug.php and get this error on that page:

Notice: Undefined index: GATEWAY_FILE in /home/XXX/domains/XXX.com/public_html/plugins/zoocart_payment/ideal/idealcheckout/includes/library.php on line 722

Notice: Undefined index: GATEWAY_FILE in /home/XXX/domains/XXX.com/public_html/plugins/zoocart_payment/ideal/idealcheckout/includes/library.php on line 726

Notice: Undefined index: GATEWAY_FILE in /home/XXX/domains/XXX.com/public_html/plugins/zoocart_payment/ideal/idealcheckout/includes/init.php on line 215

Notice: Undefined index: GATEWAY_FILE in /home/XXX/domains/XXX.com/public_html/plugins/zoocart_payment/ideal/idealcheckout/includes/init.php on line 217
ERROR: Cannot load gateway file "".

FILE: /home/XXX/domains/XXX.com/public_html/plugins/zoocart_payment/ideal/idealcheckout/includes/init.php

LINE: 217

Hope you are able to help?

Regards,
Merlin

**Comment by malles** [comment]
Try my plugin for Mollie ;) https://github.com/Bixie/Zoolander-ZOOcart-Mollie
