### ISSUE TITLE
ZOOcart iDEAL Mollie possible?

### ISSUE THREAD

**Issue by FranklinKramer** [Bixie/Zoolander-ZOOcart-iDEAL#4]
Is it possible to use Mollie as a Payment provider in combination with this plugin?

**Comment by malles** [comment]
That gateway has not been modified yet. It would need adjustments simular to https://github.com/Bixie/Zoolander-ZOOcart-iDEAL/commit/91dbaf357bf8a69c250fe24cf4015ed6e419000a

**Comment by FranklinKramer** [comment]
Do you have any idea if and if so, when this gateway will be modified? I expect a new assignment within a couple of weeks that might need this gateway as an payment option.

Cheers in advance for your reply.

Regards,
Franklin

**Comment by malles** [comment]
Let's put it this way; when you really need it, it can be done. It's not a big job, so it won't take long.
You can mabe try it yourself and make a PR :)

**Comment by FranklinKramer** [comment]
Great to hear that it can be done rather easily. On my account, when it comes to programming, "two left hands" will be my middle name :-)

Do you expet that you could realise this Matthijs? It would help me out a great deal.

**Comment by malles** [comment]
I started the conversion of Mollie. https://github.com/Bixie/Zoolander-ZOOcart-iDEAL/commit/1ea82ce8653cc4e3100a18f23073b9f33adb0f80.
I can't test it without test-credentials for Mollie. Can you provide those for me? (matthijs @ bixie.nl)

**Comment by FranklinKramer** [comment]
Dear Matthijs,
Sorry for not replying to this topic. Is it still possible to arrange the Mollie payment option for this plugin? What do you need from me and is it possible to send the needed credentials via e-mail?

Regards,
Franklin

**Comment by malles** [comment]
Hi Franklin,
The mollie engine has been tested by another user, and should be fine. It is active in the latest master.

If you want to use more Mollie payment methods, I also created a Mollie specific plugin for ZOOcart: https://github.com/Bixie/Zoolander-ZOOcart-Mollie
