### ISSUE TITLE
Sisow - A fatal error has occured.

### ISSUE THREAD

**Issue by milos-aleksic** [Bixie/Zoolander-ZOOcart-iDEAL#6]
It seems I'm unable to configure the checkout to work as expected. This is what I did:

1. Moved ideal-sisow folder from _ideal/idealcheckout/gateways/disabled/_ to _ideal/idealcheckout/gateways/_
2. Selected the gateway in plugin params for: Type iDEAL param
3. Set the provided credentials in params (see attached), I tried different possibilities I saw for other payments, but always the message is the same, it seems like I'm not reaching this point...

I constantly get a __A fatal error has occured.__ message, and if I check the log from /plugins/zoocart_payment/ideal/idealcheckout/temp/ I see the following message: 

```
TEXT: ERROR: Cannot load gateway file "".
FILE: /plugins/zoocart_payment/ideal/idealcheckout/includes/init.php
LINE: 217
```

Could you please give me some instructions on how I could debug it further? If you are familiarized with this behavior or I clearly did something wrong would appreciate if you could provide me with instructions on how to fix it.

Thanks in advance

![glasscase administration plugin manager zoocart ideal payment](https://cloud.githubusercontent.com/assets/2932588/6306623/eb93a00c-b902-11e4-80ff-97f0cf46f51c.png)

**Comment by malles** [comment]
Hi,
There are some steps to convert a gateway to be used in the plugin. Best way is to check how others are done: https://github.com/Bixie/Zoolander-ZOOcart-iDEAL/commit/91dbaf357bf8a69c250fe24cf4015ed6e419000a
You get the fatal error because the config is not read by the gateway. The `config.xml` has to be replaced by a `config.json` that couples the config fields with the joomla-plugin fields.

**Comment by malles** [comment]
Hi Milos,
I started the conversion of Sisow. https://github.com/Bixie/Zoolander-ZOOcart-iDEAL/commit/00757ca52c0cf5ebc7e0acb12e9a5d360f203762
I just did the basics now, but I can't really test any further without test-credentials. Can you provide a test-account for Sisow?
You can test yourself by downloading and installing the [develop branche](https://github.com/Bixie/Zoolander-ZOOcart-iDEAL/archive/develop.zip)

**Comment by malles** [comment]
I tested the method, and it seems fine. I can't test the push-url, since I develop on my localhost. Please test the [develop version](https://github.com/Bixie/Zoolander-ZOOcart-iDEAL/archive/develop.zip).

**Comment by malles** [comment]
Hi Milos,
Can you confirm this gateway working correctly? If so, it could be merged into master.

**Comment by milos-aleksic** [comment]
Yes Matthijs, sorry.

We were not able to go live yet, but all tests are positive. I think you can merge it without problems. Will let you know if due to any reason something changes.

Thanks a lot!

**Comment by malles** [comment]
Great, thanks!
